[package]
name = "voting"
version = "0.0.1"
# upgradeable
upgrade_policy = "compatible"

[addresses]
my_addrx="_"

[dev-addresses]
my_addrx="0xf72393cbd63a3e3c476c067c761b6f57d3f44943cd720290f8584064cf53b26d"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
