[package]
name = "voting"
version = "0.0.1"
# upgradeable
upgrade_policy = "compatible"

[addresses]
my_addrx="_"

[dev-addresses]
my_addrx="0xc9894f0373c00ea85750edc57c10dce4e34ee0592a84cca81a7b1b0665308911"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
